citations = [
	{"citation": "La mayor gloria no está en no caer nunca, sino en levantarse de nuevo cada vez que caes.", "autor": "Confucius"},
	{"citation": "La felicidad no es algo ya hecho. Proviene de tus propias acciones.", "autor": "Dalaï Lama"},
	{"citation": "La vida es como una bicicleta, hay que seguir avanzando para mantener el equilibrio.", "autor": "Albert Einstein"},
	{"citation": "El único viaje real no sería a nuevos paisajes, sino a nuevos ojos.", "autor": "Marcel Proust"},
	{"citation": "La persona que mueve una montaña empieza moviendo pequeñas piedras.", "autor": "Confucius"},
	{"citation": "La imaginación es más importante que el conocimiento.", "autor": "Albert Einstein"},
	{"citation": "Sólo hay una forma de fracasar, y es rendirse antes de haberlo conseguido.", "autor": "Georges Clémenceau"},
	{"citation": "Nada puede hacerse sin un poco de entusiasmo.", "autor": "Voltaire"},
	{"citation": "La felicidad depende sólo de nosotros.", "autor": "Aristote"},
	{"citation": "La paciencia es amarga, pero su fruto es dulce.", "autor": "Jean-Jacques Rousseau"},
	{"citation": "La vida es como una bicicleta: tienes que seguir moviéndote si no quieres perder el equilibrio.", "autor": "Albert Einstein"},
	{"citation": "El amor es lo único que crece cuando se comparte.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "Se necesita toda una vida para aprender a vivir.", "autor": "Sénèque"},
	{"citation": "Coraje significa entender tu propia vida.", "autor": "Jean-Paul Sartre"},
	{"citation": "La libertad es independencia de pensamiento.", "autor": "Épictète"},
	{"citation": "La vida es demasiado corta para ser pequeño.", "autor": "Benjamin Disraeli"},
	{"citation": "Nada desarrolla tanto la inteligencia como viajar.", "autor": "Émile Zola"},
	{"citation": "El verdadero viajero no sabe adónde va.", "autor": "Lao Tseu"},
	{"citation": "El futuro depende de lo que hagamos en el presente.", "autor": "Mahatma Gandhi"},
	{"citation": "La ciencia es algo hermoso cuando no tienes que ganarte la vida con ella.", "autor": "Albert Einstein"},
	{"citation": "La educación es el arma más poderosa para cambiar el mundo.", "autor": "Nelson Mandela"},
	{"citation": "El mayor secreto de la felicidad es sentirse bien con uno mismo.", "autor": "Bernard Fontenelle"},
	{"citation": "La vida es lo que ocurre cuando has planeado otra cosa.", "autor": "John Lennon"},
	{"citation": "Coraje significa entender tu propia vida...", "autor": "Jean-Paul Sartre"},
	{"citation": "Todo hombre es culpable de todo el bien que no ha hecho.", "autor": "Voltaire"},
	{"citation": "La vida es un reto que hay que superar, una felicidad que hay que ganarse, una aventura que hay que intentar.", "autor": "Mère Teresa"},
	{"citation": "No hay genio sin un toque de locura.", "autor": "Aristote"},
	{"citation": "Es más fácil renunciar a tus deseos que complacerlos.", "autor": "Sigmund Freud"},
	{"citation": "Siempre eres responsable de lo que domesticas.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "Nada es real excepto los sueños y el amor.", "autor": "Anna de Noailles"},
	{"citation": "Las pasiones son todas buenas por naturaleza, y no tenemos nada que evitar salvo su mal uso o su exceso.", "autor": "René Descartes"},
	{"citation": "La vejez es un naufragio.", "autor": "Charles de Gaulle"},
	{"citation": "Los grandes logros siempre van precedidos de grandes pensamientos.", "autor": "Steve Jobs"},
	{"citation": "La vida feliz es aquella que está en sintonía con su propia naturaleza.", "autor": "Sénèque"},
	{"citation": "Una vez cruzada la línea, ya no hay límites.", "autor": "Alfred Jarry"},
	{"citation": "No esperes a que las cosas sucedan como tú quieres; decide querer lo que sucede y serás feliz.", "autor": "Epictète"},
	{"citation": "El destino baraja las cartas, pero nosotros las jugamos.", "autor": "Arthur Schopenhauer"},
	{"citation": "La felicidad no consiste en buscar la perfección, sino en tolerar la imperfección.", "autor": "Siddhartha Mukherjee"},
	{"citation": "No vemos las cosas como son, las vemos como somos.", "autor": "Anaïs Nin"},
	{"citation": "Lo que somos es el resultado de lo que hemos pensado.", "autor": "Bouddha"},
	{"citation": "Haga de su vida un sueño, y de su sueño una realidad.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "Es mejor fracasar en la originalidad que triunfar en la imitación.", "autor": "Herman Melville"},
	{"citation": "El arte del éxito consiste en saber rodearse de los mejores.", "autor": "John Fitzgerald Kennedy"},
	{"citation": "El éxito significa ir de fracaso en fracaso sin perder el entusiasmo.", "autor": "Winston Churchill"},
	{"citation": "Dentro de veinte años, estarás más decepcionado por las cosas que no hiciste que por las que hiciste.", "autor": "Mark Twain"},
	{"citation": "La vida es lo que ocurre cuando estás ocupado haciendo otros planes.", "autor": "John Lennon"},
	{"citation": "Un problema sin solución es un problema mal planteado.", "autor": "Albert Einstein"},
	{"citation": "Sueña tu vida en color, es el secreto de la felicidad.", "autor": "Walt Disney"},
	{"citation": "No hay nada en la inteligencia que no estuviera primero en los sentidos.", "autor": "Aristote"},
	{"citation": "La verdadera nobleza consiste en ser superiores a la persona que éramos ayer.", "autor": "Ernest Hemingway"},
	{"citation": "Vivir es convertir tu sueño en un recuerdo.", "autor": "Oscar Wilde"},
	{"citation": "La experiencia es como una linterna a la espalda, que sólo ilumina el camino recorrido.", "autor": "Confucius"},
	{"citation": "La felicidad es un viaje, no un destino.", "autor": "proverbio chino"},
	{"citation": "No hay viento favorable para quien no sabe adónde va.", "autor": "Sénèque"},
	{"citation": "La perseverancia es el secreto de todos los triunfos.", "autor": "Victor Hugo"},
	{"citation": "El alma no tiene ningún secreto que la conducta no revele.", "autor": "Lao-Tseu"},
	{"citation": "Lo esencial es invisible a los ojos.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "Sólo hay una forma de evitar las críticas: no hacer nada, no decir nada y no ser nada.", "autor": "Aristote"},
	{"citation": "La vida es demasiado corta para pasarla lamentando todo lo que no tuvimos el valor de intentar.", "autor": "Marie-Claude Bibeau"},
	{"citation": "La verdadera felicidad cuesta poco; si es cara, no es de la buena.", "autor": "Chateaubriand"},
	{"citation": "Quien no recuerda el pasado está condenado a repetirlo.", "autor": "George Santayana"},
	{"citation": "El amor no ve con los ojos, sino con el alma.", "autor": "William Shakespeare"},
	{"citation": "Nunca eres feliz donde estás.", "autor": "Molière"},
	{"citation": "Es mejor que te odien por lo que eres a que te amen por lo que no eres.", "autor": "André Gide"},
	{"citation": "Siempre hay un elemento de locura en el amor. Pero también hay siempre un elemento de razón en la locura.", "autor": "Friedrich Nietzsche"},
	{"citation": "Las grandes cosas no las consiguen quienes ceden a las tendencias, las modas y las pasiones del momento.", "autor": "Jack Kerouac"},
	{"citation": "El hombre nace libre y en todas partes está encadenado.", "autor": "Jean-Jacques Rousseau"},
	{"citation": "El corazón tiene sus razones que la razón desconoce.", "autor": "Blaise Pascal"},
	{"citation": "La mayor desgracia de los hombres es que no piensan.", "autor": "Blaise Pascal"},
	{"citation": "La verdadera generosidad hacia el futuro significa darlo todo por el presente.", "autor": "Albert Camus"},
	{"citation": "Sólo hay una felicidad en la vida, y es amar y ser amado.", "autor": "George Sand"},
	{"citation": "Sólo puedes ver con claridad con el corazón. Lo esencial es invisible a los ojos.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "Nada es más peligroso que una idea, cuando todo lo que tienes es una idea.", "autor": "Alain"},
	{"citation": "La ignorancia es la madre de todos los males.", "autor": "François Rabelais"},
	{"citation": "La mejor manera de lograr lo imposible es creer que es posible.", "autor": "Alice au Pays des Merveilles"},
	{"citation": "Pienso, luego existo.", "autor": "René Descartes"},
	{"citation": "El hombre es un lobo para el hombre.", "autor": "Thomas Hobbes"},
	{"citation": "La libertad de una persona termina donde empieza la de otra.", "autor": "John Stuart Mill"},
	{"citation": "Un poco de ciencia te aleja de Dios, pero mucha te trae de vuelta.", "autor": "Louis Pasteur"},
	{"citation": "El conocimiento se adquiere a través de la experiencia, todo lo demás es sólo información.", "autor": "Albert Einstein"},
	{"citation": "Quizá la grandeza de una profesión resida sobre todo en unir a las personas: sólo hay un verdadero lujo y son las relaciones humanas.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "El futuro es sólo el presente que hay que poner en orden. No tienes que preverlo, sólo permitir que suceda.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "Es el tiempo que has perdido con tu rosa lo que hace que tu rosa sea tan importante.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "Apunta siempre a la luna, porque aunque fracases, aterrizarás en las estrellas.", "autor": "Oscar Wilde"},
	{"citation": "La vida es un misterio que hay que vivir, no un problema que hay que resolver.", "autor": "Gandhi"},
	{"citation": "Los únicos límites a lo que podemos conseguir mañana son las dudas que tenemos hoy.", "autor": "Franklin D. Roosevelt"},
	{"citation": "La felicidad a veces se esconde en lo desconocido.", "autor": "Victor Hugo"},
	{"citation": "Lo importante no es convencer, sino hacer reflexionar.", "autor": "Bernard Werber"},
	{"citation": "El infierno son los demás.", "autor": "Jean-Paul Sartre"},
	{"citation": "Vivir sin esperanza es dejar de vivir.", "autor": "Fiodor Dostoïevski"},
	{"citation": "No se nace mujer: se llega a serlo.", "autor": "Simone de Beauvoir"},
	{"citation": "Sólo hay una cosa que puede hacer imposible un sueño, y es el miedo a fracasar.", "autor": "Paulo Coelho"},
	{"citation": "La locura es lo único de lo que nunca te arrepientes.", "autor": "Oscar Wilde"},
	{"citation": "La vida es como una bicicleta, tienes que seguir moviéndote para mantener el equilibrio.", "autor": "Albert Einstein"},
	{"citation": "No busco las respuestas, busco entender las preguntas.", "autor": "Confucius"},
	{"citation": "La gente construye demasiados muros y pocos puentes.", "autor": "Isaac Newton"},
	{"citation": "Lo único que debemos temer es al propio miedo.", "autor": "Franklin D. Roosevelt"},
	{"citation": "Lo que hacemos en nuestra vida resuena en la eternidad.", "autor": "Maximus Decimus"},
	{"citation": "Puedes derrotar a mil mil hombres en la batalla, pero el mayor conquistador es el que se derrota a sí mismo.", "autor": "Bouddha"},
	{"citation": "El secreto del cambio es concentrar tu energía en crear lo nuevo, no en luchar contra lo viejo.", "autor": "Socrate"},
	{"citation": "La inteligencia es la capacidad de adaptarse al cambio.", "autor": "Stephen Hawking"},
	{"citation": "La vida es una flor. El amor es su miel.", "autor": "Victor Hugo"},
	{"citation": "Somos lo que hacemos repetidamente. Así que la excelencia no es un acto, sino un hábito.", "autor": "Aristote"},
	{"citation": "Todo lo que la mente puede concebir y creer, puede lograrlo.", "autor": "Napoleon Hill"},
	{"citation": "La verdadera libertad significa poder hacer todo sin perjudicar a los demás.", "autor": "Charles de Montesquieu"},
	{"citation": "El único lugar donde el éxito está por encima del trabajo es en el diccionario.", "autor": "Vidal Sassoon"},
	{"citation": "La vida es una serie de lecciones que hay que vivir para entenderlas.", "autor": "Helen Keller"},
	{"citation": "Haz de tu vida un sueño, y de un sueño una realidad.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "La felicidad no es un objetivo, es una forma de vida.", "autor": "Margaret Lee Runbeck"},
	{"citation": "Sólo los que se atreven a ir demasiado lejos descubren hasta dónde se puede llegar.", "autor": "T. S. Eliot"},
	{"citation": "No juzgues cada día por la cosecha que recoges, sino por las semillas que siembras.", "autor": "Robert Louis Stevenson"},
	{"citation": "Nada es permanente, excepto el cambio.", "autor": "Héraclite"},
	{"citation": "La única forma de hacer un buen trabajo es amar lo que haces.", "autor": "Steve Jobs"},
	{"citation": "La mejor manera de predecir el futuro es crearlo.", "autor": "Peter Drucker"},
	{"citation": "La sencillez es la máxima sofisticación.", "autor": "Léonard de Vinci"},
	{"citation": "Sé el cambio que quieres ver en el mundo.", "autor": "Mahatma Gandhi"},
	{"citation": "Los sueños no se hacen realidad por arte de magia, sino que requieren determinación y trabajo duro.", "autor": "Colin Powell"},
	{"citation": "Un pesimista ve dificultades en cada oportunidad, un optimista ve oportunidades en cada dificultad.", "autor": "Winston Churchill"},
	{"citation": "Si no planeas, planeas fracasar.", "autor": "Benjamin Franklin"},
	{"citation": "El éxito significa caerse siete veces y volver a levantarse ocho.", "autor": "proverbio japonés"},
	{"citation": "El mayor obstáculo para el éxito es el miedo al fracaso.", "autor": "Sven Goran Eriksson"},
	{"citation": "La felicidad no está en la posesión de bienes, sino en el disfrute de las cosas.", "autor": "Jean-Jacques Rousseau"},
	{"citation": "La acción es la clave fundamental del éxito.", "autor": "Pablo Picasso"},
	{"citation": "Es más fácil cambiar uno mismo que cambiar el mundo.", "autor": "Gandhi"},
	{"citation": "El éxito es de todos. Todo depende del trabajo en equipo.", "autor": "François Mitterrand"},
	{"citation": "El mayor fracaso es no tener el valor de atreverse.", "autor": "André Gide"},
	{"citation": "No hay sustituto para la honestidad.", "autor": "Warren Buffett"},
	{"citation": "La sabiduría comienza con el asombro.", "autor": "Socrate"},
	{"citation": "Las palabras son ventanas (o paredes).", "autor": "Marshall Rosenberg"},
	{"citation": "El mayor enemigo del éxito es el miedo al fracaso.", "autor": "Charles F. Kettering"},
	{"citation": "Las únicas cosas de valor son las que compartimos.", "autor": "Jean-Paul Sartre"},
	{"citation": "Los sueños necesitan trabajo para hacerse realidad.", "autor": "Pablo Neruda"},
	{"citation": "No estamos conquistando la montaña, nos estamos conquistando a nosotros mismos.", "autor": "Sir Edmund Hillary"},
	{"citation": "La vida es lo que hacemos de ella. Siempre lo ha sido, siempre lo será.", "autor": "Eleanor Roosevelt"},
	{"citation": "No hay camino hacia la felicidad. La felicidad es el camino.", "autor": "Bouddha"},
	{"citation": "La felicidad está hecha de pequeñas cosas: una sonrisa, un encuentro, una buena comida.", "autor": "Jean de La Fontaine"},
	{"citation": "El único viaje real es descubrir los paisajes desconocidos que llevamos dentro.", "autor": "Marcel Proust"},
	{"citation": "Nunca es demasiado tarde para ser lo que podrías haber sido.", "autor": "George Eliot"},
	{"citation": "Lo importante no es tener una vida larga, sino una vida llena de sentido.", "autor": "Sénèque"},
	{"citation": "El mayor error que se puede cometer en la vida es tener siempre miedo a equivocarse.", "autor": "Elbert Hubbard"},
	{"citation": "El mayor obstáculo para el progreso es el miedo al cambio.", "autor": "John F. Kennedy"},
	{"citation": "En la vida hay que elegir. Nuestras elecciones dan forma a nuestras vidas.", "autor": "Jean-Paul Sartre"},
	{"citation": "El futuro pertenece a quienes creen en la belleza de sus sueños.", "autor": "Eleanor Roosevelt"},
	{"citation": "La felicidad es una elección, no una consecuencia.", "autor": "Ralph Marston"},
	{"citation": "Todo lo que no nos mata nos hace más fuertes.", "autor": "Friedrich Nietzsche"},
	{"citation": "Las grandes cosas no suceden por impulso, sino por una serie de pequeñas cosas que confluyen.", "autor": "Vincent Van Gogh"},
	{"citation": "La vida o es una aventura atrevida o no es nada.", "autor": "Helen Keller"},
	{"citation": "Todo lo que somos es el resultado de lo que hemos pensado.", "autor": "Bouddha"},
	{"citation": "La vida es corta, pero lo bastante larga para hacer lo correcto.", "autor": "Épictète"},
	{"citation": "La mejor manera de predecir el futuro es inventarlo.", "autor": "Alan Kay"},
	{"citation": "La vida no consiste en esperar a que pase la tormenta, sino en aprender a bailar bajo la lluvia.", "autor": "Vivian Greene"},
	{"citation": "La verdadera grandeza consiste en ser superiores a la persona que éramos ayer.", "autor": "Ernest Hemingway"},
	{"citation": "La vida es demasiado corta para pasarla lamentándose.", "autor": "proverbio chino"},
	{"citation": "Los únicos fracasos reales son los que no intentas superar.", "autor": "John C. Maxwell"},
	{"citation": "La mejor manera de hacer amigos es serlo.", "autor": "Ralph Waldo Emerson"},
	{"citation": "No hay éxito sin fracaso.", "autor": "Louis Pasteur"},
	{"citation": "Cada día es una nueva oportunidad de cambiar tu vida.", "autor": "desconocido"},
	{"citation": "No se puede cruzar el mar con sólo mirar el agua.", "autor": "Rabindranath Tagore"},
	{"citation": "La única manera de hacer un gran trabajo es amar lo que haces.", "autor": "Steve Jobs"},
	{"citation": "Si quieres vivir una vida feliz, apégala a un objetivo, no a personas o cosas.", "autor": "Albert Einstein"},
	{"citation": "Los grandes pensamientos salen del corazón.", "autor": "Luc de Clapiers"},
	{"citation": "No se trata de la duración de la vida, sino de su profundidad.", "autor": "Ralph Waldo Emerson"},
	{"citation": "Lo único que realmente puedes controlar es tu actitud.", "autor": "desconocido"},
	{"citation": "El mejor viaje es el que conduce al autodescubrimiento.", "autor": "proverbio chino"},
	{"citation": "La felicidad suele ser el resultado de una actitud positiva.", "autor": "desconocido"},
	{"citation": "El verdadero coraje significa enfrentarse a la realidad.", "autor": "Alain"},
	{"citation": "La vida no consiste en esperar a que pasen las tormentas, sino en aprender a bailar bajo la lluvia.", "autor": "Vivian Greene"},
	{"citation": "La felicidad es una dirección, no un destino.", "autor": "Sydney J. Harris"},
	{"citation": "El éxito pertenece a quienes creen en la belleza de sus sueños.", "autor": "Eleanor Roosevelt"},
	{"citation": "Todo lo que puedas hacer o sueñes hacer, empieza a hacerlo. La audacia tiene genio, poder y magia.", "autor": "Johann Wolfgang von Goethe"},
	{"citation": "El verdadero viaje de descubrimiento no consiste en buscar nuevos paisajes, sino en ver con nuevos ojos.", "autor": "Marcel Proust"},
	{"citation": "Lo que no nos mata nos hace más fuertes.", "autor": "Friedrich Nietzsche"},
	{"citation": "Cada dificultad encontrada debe ser una oportunidad para seguir avanzando.", "autor": "Pierre de Coubertin"},
	{"citation": "La vida es demasiado corta para pasar tiempo con gente que no se preocupa.", "autor": "desconocido"},
	{"citation": "La felicidad es una forma de viajar, no un destino.", "autor": "Roy Goodman"},
	{"citation": "Es más fácil pedir perdón que permiso.", "autor": "Grace Hopper"},
	{"citation": "La mejor manera de realizarse es ayudar a los demás a alcanzar sus sueños.", "autor": "desconocido"},
	{"citation": "Los únicos límites que existen son los que te impones a ti mismo.", "autor": "desconocido"},
	{"citation": "La gente no está contra ti; está a favor de sí misma.", "autor": "desconocido"},
	{"citation": "Lo importante no es lo que tienes, sino lo que haces con lo que tienes.", "autor": "desconocido"},
	{"citation": "No hay mejor momento para empezar que ahora.", "autor": "desconocido"},
	{"citation": "La pasión es la clave del éxito.", "autor": "desconocido"},
	{"citation": "El mejor viaje comienza con el primer paso.", "autor": "Lao Tseu"},
	{"citation": "Los sueños son las respuestas de hoy a las preguntas de mañana.", "autor": "desconocido"},
	{"citation": "La vida es lo que tú haces de ella.", "autor": "Eleanor Roosevelt"},
]