citations = [
	{"citation": "The greatest glory is not in never falling, but in rising again every time you fall.", "autor": "Confucius"},
	{"citation": "Happiness is not something ready-made. It comes from your own actions.", "autor": "Dalaï Lama"},
	{"citation": "Life is like a bicycle, you have to keep moving to keep your balance.", "autor": "Albert Einstein"},
	{"citation": "The only real journey wouldn't be to new landscapes, but to new eyes.", "autor": "Marcel Proust"},
	{"citation": "He who moves a mountain begins by moving small stones.", "autor": "Confucius"},
	{"citation": "Imagination is more important than knowledge.", "autor": "Albert Einstein"},
	{"citation": "There's only one way to fail, and that's to give up before you've succeeded.", "autor": "Georges Clémenceau"},
	{"citation": "Nothing can be done without a little enthusiasm.", "autor": "Voltaire"},
	{"citation": "Happiness depends on us alone.", "autor": "Aristote"},
	{"citation": "Patience is bitter, but its fruit is sweet.", "autor": "Jean-Jacques Rousseau"},
	{"citation": "Life is like a bicycle: you have to keep moving forward to keep your balance.", "autor": "Albert Einstein"},
	{"citation": "Love is the only thing that grows when shared.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "It takes a lifetime to learn how to live.", "autor": "Sénèque"},
	{"citation": "Courage means understanding your own life.", "autor": "Jean-Paul Sartre"},
	{"citation": "Freedom is independence of thought.", "autor": "Épictète"},
	{"citation": "Life is too short to be small.", "autor": "Benjamin Disraeli"},
	{"citation": "Nothing develops intelligence like travel.", "autor": "Émile Zola"},
	{"citation": "The true traveler doesn't know where he's going.", "autor": "Lao Tseu"},
	{"citation": "The future depends on what we do in the present.", "autor": "Mahatma Gandhi"},
	{"citation": "Science is a beautiful thing when you don't have to make a living out of it.", "autor": "Albert Einstein"},
	{"citation": "Education is the most powerful weapon for changing the world.", "autor": "Nelson Mandela"},
	{"citation": "The greatest secret to happiness is to feel good about yourself.", "autor": "Bernard Fontenelle"},
	{"citation": "Life is what happens when you've planned for something else.", "autor": "John Lennon"},
	{"citation": "Courage is understanding your own life...", "autor": "Jean-Paul Sartre"},
	{"citation": "Every man is guilty of all the good he has not done.", "autor": "Voltaire"},
	{"citation": "Life is a challenge to be met, a happiness to be earned, an adventure to be attempted.", "autor": "Mère Teresa"},
	{"citation": "There is no genius without a touch of madness.", "autor": "Aristote"},
	{"citation": "It's easier to give up your desires than to satisfy them.", "autor": "Sigmund Freud"},
	{"citation": "You're always responsible for what you tame.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "Nothing is real except dreams and love.", "autor": "Anna de Noailles"},
	{"citation": "Passions are all good by nature, and we have nothing to avoid but their misuse or excess.", "autor": "René Descartes"},
	{"citation": "Old age is a shipwreck.", "autor": "Charles de Gaulle"},
	{"citation": "Great achievements are always preceded by great thoughts.", "autor": "Steve Jobs"},
	{"citation": "The happy life is one that is in tune with its own nature.", "autor": "Sénèque"},
	{"citation": "Once you've crossed the line, there are no more limits.", "autor": "Alfred Jarry"},
	{"citation": "Don't wait for events to happen as you wish; decide to want what happens and you'll be happy.", "autor": "Epictète"},
	{"citation": "Fate shuffles the cards, but we play them.", "autor": "Arthur Schopenhauer"},
	{"citation": "Happiness lies not in the quest for perfection, but in tolerating imperfection.", "autor": "Siddhartha Mukherjee"},
	{"citation": "We don't see things as they are, we see them as we are.", "autor": "Anaïs Nin"},
	{"citation": "What we are is the result of what we have thought.", "autor": "Bouddha"},
	{"citation": "Make your life a dream, and your dream a reality.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "It's better to fail at originality than to succeed at imitation.", "autor": "Herman Melville"},
	{"citation": "The art of success lies in knowing how to surround yourself with the best.", "autor": "John Fitzgerald Kennedy"},
	{"citation": "Success is going from failure to failure without losing your enthusiasm.", "autor": "Winston Churchill"},
	{"citation": "Twenty years from now, you'll be more disappointed by the things you didn't do than by the things you did do.", "autor": "Mark Twain"},
	{"citation": "Life is what happens when you're busy making other plans.", "autor": "John Lennon"},
	{"citation": "A problem without a solution is a problem badly posed.", "autor": "Albert Einstein"},
	{"citation": "Dream your life in color, it's the secret of happiness.", "autor": "Walt Disney"},
	{"citation": "There is nothing in intelligence that was not first in the senses.", "autor": "Aristote"},
	{"citation": "True nobility consists in being superior to who we were yesterday.", "autor": "Ernest Hemingway"},
	{"citation": "To live is to turn your dream into a memory.", "autor": "Oscar Wilde"},
	{"citation": "Experience is like a lantern on your back, illuminating only the path you've taken.", "autor": "Confucius"},
	{"citation": "Happiness is a journey, not a destination.", "autor": "Chinese proverb"},
	{"citation": "There's no fair wind for those who don't know where they're going.", "autor": "Sénèque"},
	{"citation": "Perseverance is the secret of all triumphs.", "autor": "Victor Hugo"},
	{"citation": "The soul has no secret that conduct does not reveal.", "autor": "Lao-Tseu"},
	{"citation": "The essential is invisible to the eye.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "There's only one way to avoid criticism: do nothing, say nothing and be nothing.", "autor": "Aristote"},
	{"citation": "Life's too short to spend it regretting everything you didn't have the courage to try.", "autor": "Marie-Claude Bibeau"},
	{"citation": "True happiness costs little; if it's expensive, it's not a good kind.", "autor": "Chateaubriand"},
	{"citation": "Those who cannot remember the past are condemned to repeat it.", "autor": "George Santayana"},
	{"citation": "Love sees not with the eyes but with the soul.", "autor": "William Shakespeare"},
	{"citation": "You're never happy where you are.", "autor": "Molière"},
	{"citation": "It's better to be hated for what you are, than to be loved for what you're not.", "autor": "André Gide"},
	{"citation": "There's always an element of madness in love. But there's also always an element of reason in madness.", "autor": "Friedrich Nietzsche"},
	{"citation": "Great things are not achieved by those who give in to the trends, fads and passions of the moment.", "autor": "Jack Kerouac"},
	{"citation": "Man is born free, and everywhere he is in irons.", "autor": "Jean-Jacques Rousseau"},
	{"citation": "The heart has its reasons that reason does not know.", "autor": "Blaise Pascal"},
	{"citation": "The greatest misfortune of men is that they don't think.", "autor": "Blaise Pascal"},
	{"citation": "True generosity towards the future means giving everything to the present.", "autor": "Albert Camus"},
	{"citation": "There's only one happiness in life, and that's to love and be loved.", "autor": "George Sand"},
	{"citation": "You can only see well with your heart. What is essential is invisible to the eye.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "Nothing is more dangerous than an idea, when all you have is an idea.", "autor": "Alain"},
	{"citation": "Ignorance is the mother of all evils.", "autor": "François Rabelais"},
	{"citation": "The best way to achieve the impossible is to believe it's possible.", "autor": "Alice au Pays des Merveilles"},
	{"citation": "I think, therefore I am.", "autor": "René Descartes"},
	{"citation": "Man is a wolf to man.", "autor": "Thomas Hobbes"},
	{"citation": "One person's freedom ends where another's begins.", "autor": "John Stuart Mill"},
	{"citation": "A little science takes you away from God, but a lot brings you back.", "autor": "Louis Pasteur"},
	{"citation": "Knowledge is acquired through experience, everything else is just information.", "autor": "Albert Einstein"},
	{"citation": "Perhaps the greatness of a profession lies first and foremost in uniting people: there is only one true luxury, and that is human relationships.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "The future is only ever the present to be put in order. You don't have to foresee it, but to allow it.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "It's the time you've wasted on your rose that makes your rose so important.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "Always aim for the moon, because even if you fail, you'll land in the stars.", "autor": "Oscar Wilde"},
	{"citation": "Life is a mystery to be lived, not a problem to be solved.", "autor": "Gandhi"},
	{"citation": "The only limits to tomorrow's achievements are today's doubts.", "autor": "Franklin D. Roosevelt"},
	{"citation": "Happiness is sometimes hidden in the unknown.", "autor": "Victor Hugo"},
	{"citation": "The important thing is not to convince, but to give food for thought.", "autor": "Bernard Werber"},
	{"citation": "Hell is other people.", "autor": "Jean-Paul Sartre"},
	{"citation": "To live without hope is to cease living.", "autor": "Fiodor Dostoïevski"},
	{"citation": "You're not born a woman: you become one.", "autor": "Simone de Beauvoir"},
	{"citation": "There's only one thing that can make a dream impossible, and that's the fear of failure.", "autor": "Paulo Coelho"},
	{"citation": "Crazy things are the only things you never regret.", "autor": "Oscar Wilde"},
	{"citation": "Life is like a bicycle: you have to keep moving to keep your balance.", "autor": "Albert Einstein"},
	{"citation": "I don't want to know the answers, I want to understand the questions.", "autor": "Confucius"},
	{"citation": "Men build too many walls and not enough bridges.", "autor": "Isaac Newton"},
	{"citation": "The only thing we have to fear is fear itself.", "autor": "Franklin D. Roosevelt"},
	{"citation": "What we do in life resonates in eternity.", "autor": "Maximus Decimus"},
	{"citation": "You can defeat a thousand thousand men in battle, but the greatest conqueror is the one who defeats himself.", "autor": "Bouddha"},
	{"citation": "The secret of change is to focus your energy on creating the new, not fighting the old.", "autor": "Socrate"},
	{"citation": "Intelligence is the ability to adapt to change.", "autor": "Stephen Hawking"},
	{"citation": "Life is a flower. Love is its honey.", "autor": "Victor Hugo"},
	{"citation": "We are what we repeatedly do. Excellence is not an act, but a habit.", "autor": "Aristote"},
	{"citation": "Whatever the mind can conceive and believe, it can accomplish.", "autor": "Napoleon Hill"},
	{"citation": "True freedom means being able to do anything without harming others.", "autor": "Charles de Montesquieu"},
	{"citation": "The only place where success comes before work is in the dictionary.", "autor": "Vidal Sassoon"},
	{"citation": "Life is a series of lessons that must be lived to be understood.", "autor": "Helen Keller"},
	{"citation": "Make your life a dream, and a dream a reality.", "autor": "Antoine de Saint-Exupéry"},
	{"citation": "Happiness is not a goal, it's a way of life.", "autor": "Margaret Lee Runbeck"},
	{"citation": "Only those who dare to go too far find out just how far you can go.", "autor": "T. S. Eliot"},
	{"citation": "Don't judge each day by the harvest you reap, but by the seeds you sow.", "autor": "Robert Louis Stevenson"},
	{"citation": "Nothing is permanent, except change.", "autor": "Héraclite"},
	{"citation": "The only way to do good work is to love what you do.", "autor": "Steve Jobs"},
	{"citation": "The best way to predict the future is to create it.", "autor": "Peter Drucker"},
	{"citation": "Simplicity is the ultimate sophistication.", "autor": "Léonard de Vinci"},
	{"citation": "Be the change you want to see in the world.", "autor": "Mahatma Gandhi"},
	{"citation": "Dreams don't magically become reality; they take determination and hard work.", "autor": "Colin Powell"},
	{"citation": "A pessimist sees difficulty in every opportunity, an optimist sees opportunity in every difficulty.", "autor": "Winston Churchill"},
	{"citation": "Failure to plan is planning to fail.", "autor": "Benjamin Franklin"},
	{"citation": "Success is falling down seven times, getting back up eight.", "autor": "Japanese proverb"},
	{"citation": "The biggest obstacle to success is the fear of failure.", "autor": "Sven Goran Eriksson"},
	{"citation": "Happiness is not in the possession of goods, but in the enjoyment of things.", "autor": "Jean-Jacques Rousseau"},
	{"citation": "Action is the fundamental key to success.", "autor": "Pablo Picasso"},
	{"citation": "It's easier to change yourself than to change the world.", "autor": "Gandhi"},
	{"citation": "Success belongs to everyone. It's all about teamwork.", "autor": "François Mitterrand"},
	{"citation": "The greatest failure is not having the courage to dare.", "autor": "André Gide"},
	{"citation": "There's no substitute for honesty.", "autor": "Warren Buffett"},
	{"citation": "Wisdom begins in wonder.", "autor": "Socrate"},
	{"citation": "Words are windows (or walls).", "autor": "Marshall Rosenberg"},
	{"citation": "The greatest enemy of success is the fear of failure.", "autor": "Charles F. Kettering"},
	{"citation": "The only things of value are those we share.", "autor": "Jean-Paul Sartre"},
	{"citation": "Dreams need work to come true.", "autor": "Pablo Neruda"},
	{"citation": "It's not the mountain we're conquering, but ourselves.", "autor": "Sir Edmund Hillary"},
	{"citation": "Life is what we make of it. Always has been, always will be.", "autor": "Eleanor Roosevelt"},
	{"citation": "There is no path to happiness. Happiness is the path.", "autor": "Bouddha"},
	{"citation": "Happiness is made up of little things: a smile, a meeting, a good meal.", "autor": "Jean de La Fontaine"},
	{"citation": "The only real journey is to discover the unknown landscapes within ourselves.", "autor": "Marcel Proust"},
	{"citation": "It's never too late to be what you could have been.", "autor": "George Eliot"},
	{"citation": "The important thing is not to have a long life, but a life filled with meaning.", "autor": "Sénèque"},
	{"citation": "The biggest mistake you can make in life is to always be afraid of making a mistake.", "autor": "Elbert Hubbard"},
	{"citation": "The greatest obstacle to progress is the fear of change.", "autor": "John F. Kennedy"},
	{"citation": "Life is made of choices. Our choices shape our lives.", "autor": "Jean-Paul Sartre"},
	{"citation": "The future belongs to those who believe in the beauty of their dreams.", "autor": "Eleanor Roosevelt"},
	{"citation": "Happiness is a choice, not a consequence.", "autor": "Ralph Marston"},
	{"citation": "Everything that doesn't kill us makes us stronger.", "autor": "Friedrich Nietzsche"},
	{"citation": "Great things don't happen by impulse, but by a series of small things coming together.", "autor": "Vincent Van Gogh"},
	{"citation": "Life is a daring adventure, or it's nothing.", "autor": "Helen Keller"},
	{"citation": "Everything we are is the result of what we have thought.", "autor": "Bouddha"},
	{"citation": "Life is short, but it's long enough to do well.", "autor": "Épictète"},
	{"citation": "The best way to predict the future is to invent it.", "autor": "Alan Kay"},
	{"citation": "Life isn't about waiting for the storm to pass, it's about learning to dance in the rain.", "autor": "Vivian Greene"},
	{"citation": "True greatness consists in being superior to who we were yesterday.", "autor": "Ernest Hemingway"},
	{"citation": "Life is too short to spend it regretting.", "autor": "Chinese proverb"},
	{"citation": "The only real failures are the ones you don't try to overcome.", "autor": "John C. Maxwell"},
	{"citation": "The best way to make friends is to be one.", "autor": "Ralph Waldo Emerson"},
	{"citation": "There is no success without failure.", "autor": "Louis Pasteur"},
	{"citation": "Every day is a new chance to change your life.", "autor": "unknown"},
	{"citation": "You can't cross the sea just by looking at the water.", "autor": "Rabindranath Tagore"},
	{"citation": "The only way to do a great job is to love what you do.", "autor": "Steve Jobs"},
	{"citation": "If you want to live a happy life, attach it to a goal, not to people or things.", "autor": "Albert Einstein"},
	{"citation": "Great thoughts come from the heart.", "autor": "Luc de Clapiers"},
	{"citation": "It's not the length of life, but the depth of life.", "autor": "Ralph Waldo Emerson"},
	{"citation": "The only thing you can really control is your attitude.", "autor": "unknown"},
	{"citation": "The greatest journey is the one that leads to self-discovery.", "autor": "Chinese proverb"},
	{"citation": "Happiness is often the result of a positive attitude.", "autor": "unknown"},
	{"citation": "True courage means facing up to reality.", "autor": "Alain"},
	{"citation": "Life isn't about waiting for storms to pass, it's about learning to dance in the rain.", "autor": "Vivian Greene"},
	{"citation": "Happiness is a direction, not a destination.", "autor": "Sydney J. Harris"},
	{"citation": "Success belongs to those who believe in the beauty of their dreams.", "autor": "Eleanor Roosevelt"},
	{"citation": "Anything you can do or dream of doing, just start. Boldness has genius, power and magic.", "autor": "Johann Wolfgang von Goethe"},
	{"citation": "The true voyage of discovery is not about seeking out new landscapes, but about having new eyes.", "autor": "Marcel Proust"},
	{"citation": "What doesn't kill us makes us stronger.", "autor": "Friedrich Nietzsche"},
	{"citation": "Every difficulty encountered must be an opportunity for further progress.", "autor": "Pierre de Coubertin"},
	{"citation": "Life is too short to spend time with people who aren't caring.", "autor": "unknown"},
	{"citation": "Happiness is a way of travelling, not a destination.", "autor": "Roy Goodman"},
	{"citation": "It's easier to ask forgiveness than permission.", "autor": "Grace Hopper"},
	{"citation": "The best way to fulfill yourself is to help others realize their dreams.", "autor": "unknown"},
	{"citation": "The only limits that exist are the ones you impose on yourself.", "autor": "unknown"},
	{"citation": "People aren't against you; they're for themselves.", "autor": "unknown"},
	{"citation": "What matters is not what you have, but what you do with what you have.", "autor": "unknown"},
	{"citation": "There's no better time to start than now.", "autor": "unknown"},
	{"citation": "Passion is the key to success.", "autor": "unknown"},
	{"citation": "The greatest journey begins with the first step.", "autor": "Lao Tseu"},
	{"citation": "Dreams are today's answers to tomorrow's questions.", "autor": "unknown"},
	{"citation": "Life is what you make of it.", "autor": "Eleanor Roosevelt"},
]