citations = [
    {"citation": "La plus grande gloire n'est pas de ne jamais tomber, mais de se relever à chaque chute.", "autor": "Confucius"},
    {"citation": "Le bonheur n'est pas quelque chose de prêt à l'emploi. Il vient de vos propres actions.", "autor": "Dalaï Lama"},
    {"citation": "La vie c'est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre.", "autor": "Albert Einstein"},
    {"citation": "Le seul vrai voyage, ce ne serait pas d'aller vers de nouveaux paysages, mais d'avoir d'autres yeux.", "autor": "Marcel Proust"},
    {"citation": "Celui qui déplace une montagne commence par déplacer de petites pierres.", "autor": "Confucius"},
    {"citation": "L'imagination est plus importante que le savoir.", "autor": "Albert Einstein"},
    {"citation": "Il n’y a qu’une façon d’échouer, c’est d’abandonner avant d’avoir réussi.", "autor": "Georges Clémenceau"},
    {"citation": "Rien ne se fait sans un peu d’enthousiasme.", "autor": "Voltaire"},
    {"citation": "Le bonheur dépend de nous seuls.", "autor": "Aristote"},
    {"citation": "La patience est amère, mais son fruit est doux.", "autor": "Jean-Jacques Rousseau"},
    {"citation": "La vie, c'est comme une bicyclette : il faut avancer pour ne pas perdre l'équilibre.", "autor": "Albert Einstein"},
    {"citation": "L'amour est la seule chose qui grandit quand on la partage.", "autor": "Antoine de Saint-Exupéry"},
    {"citation": "Il faut toute une vie pour apprendre à vivre.", "autor": "Sénèque"},
    {"citation": "Le courage, c'est de comprendre sa propre vie.", "autor": "Jean-Paul Sartre"},
    {"citation": "La liberté, c'est l'indépendance de la pensée.", "autor": "Épictète"},
    {"citation": "La vie est trop courte pour être petite.", "autor": "Benjamin Disraeli"},
    {"citation": "Rien ne développe l'intelligence comme les voyages.", "autor": "Émile Zola"},
    {"citation": "Le vrai voyageur ne sait pas où il va.", "autor": "Lao Tseu"},
    {"citation": "Le futur dépend de ce que nous faisons dans le présent.", "autor": "Mahatma Gandhi"},
    {"citation": "La science est une belle chose quand on ne doit pas en vivre.", "autor": "Albert Einstein"},
    {"citation": "L'éducation est l'arme la plus puissante pour changer le monde.", "autor": "Nelson Mandela"},
    {"citation": "Le plus grand secret pour le bonheur, c'est d'être bien avec soi.", "autor": "Bernard Fontenelle"},
    {"citation": "La vie, c'est ce qui arrive quand on a prévu autre chose.", "autor": "John Lennon"},
    {"citation": "Le courage, c'est de comprendre sa propre vie…", "autor": "Jean-Paul Sartre"},
    {"citation": "Tout homme est coupable de tout le bien qu’il n’a pas fait.", "autor": "Voltaire"},
    {"citation": "La vie est un défi à relever, un bonheur à mériter, une aventure à tenter.", "autor": "Mère Teresa"},
    {"citation": "Il n'y a point de génie sans un grain de folie.", "autor": "Aristote"},
    {"citation": "Il est plus facile de renoncer à ses désirs que de s'y accorder des satisfactions.", "autor": "Sigmund Freud"},
    {"citation": "On est toujours responsable de ce qu'on apprivoise.", "autor": "Antoine de Saint-Exupéry"},
    {"citation": "Il n'y a rien de réel que le rêve et l'amour.", "autor": "Anna de Noailles"},
    {"citation": "Les passions sont toutes bonnes de leur nature et nous n'avons rien à éviter que leurs mauvais usages ou leurs excès.", "autor": "René Descartes"},
    {"citation": "La vieillesse est un naufrage.", "autor": "Charles de Gaulle"},
    {"citation": "Les grandes réalisations sont toujours précédées par de grandes pensées.", "autor": "Steve Jobs"},
    {"citation": "La vie heureuse est celle qui est en accord avec sa propre nature.", "autor": "Sénèque"},
    {"citation": "Quand on a dépassé les bornes, il n’y a plus de limites.", "autor": "Alfred Jarry"},
    {"citation": "N'attends pas que les événements arrivent comme tu le souhaites ; décide de vouloir ce qui arrive et tu seras heureux.", "autor": "Epictète"},
    {"citation": "Le destin bat les cartes, mais c'est nous qui les jouons.", "autor": "Arthur Schopenhauer"},
    {"citation": "Le bonheur n'est pas dans la recherche de la perfection, mais dans la tolérance de l'imperfection.", "autor": "Siddhartha Mukherjee"},
    {"citation": "Nous ne voyons pas les choses telles qu'elles sont, nous les voyons telles que nous sommes.", "autor": "Anaïs Nin"},
    {"citation": "Ce que nous sommes est le résultat de ce que nous avons pensé.", "autor": "Bouddha"},
    {"citation": "Faites de votre vie un rêve, et de votre rêve une réalité.", "autor": "Antoine de Saint-Exupéry"},
    {"citation": "Il vaut mieux échouer dans l'originalité que réussir dans l'imitation.", "autor": "Herman Melville"},
    {"citation": "L'art de la réussite consiste à savoir s'entourer des meilleurs.", "autor": "John Fitzgerald Kennedy"},
    {"citation": "Le succès c'est d'aller d'échec en échec sans perdre son enthousiasme.", "autor": "Winston Churchill"},
    {"citation": "Dans vingt ans, tu seras plus déçu par les choses que tu n'as pas faites que par celles que tu as faites.", "autor": "Mark Twain"},
    {"citation": "La vie c'est ce qui arrive quand on est occupé à faire d'autres projets.", "autor": "John Lennon"},
    {"citation": "Un problème sans solution est un problème mal posé.", "autor": "Albert Einstein"},
    {"citation": "Rêve ta vie en couleur, c'est le secret du bonheur.", "autor": "Walt Disney"},
    {"citation": "Il n'est rien dans l'intelligence qui n'ait d'abord été dans les sens.", "autor": "Aristote"},
    {"citation": "La vraie noblesse consiste à être supérieur à celui que nous étions hier.", "autor": "Ernest Hemingway"},
    {"citation": "Vivre, c'est faire de son rêve un souvenir.", "autor": "Oscar Wilde"},
    {"citation": "L'expérience est une lanterne que l'on porte sur le dos et qui n'éclaire que le chemin parcouru.", "autor": "Confucius"},
    {"citation": "Le bonheur est un voyage, non une destination.", "autor": "Proverbe chinois"},
    {"citation": "Il n'y a pas de vent favorable pour celui qui ne sait pas où il va.", "autor": "Sénèque"},
    {"citation": "La persévérance est le secret de tous les triomphes.", "autor": "Victor Hugo"},
    {"citation": "L'âme n'a pas de secret que la conduite ne révèle.", "autor": "Lao-Tseu"},
    {"citation": "L'essentiel est invisible pour les yeux.", "autor": "Antoine de Saint-Exupéry"},
    {"citation": "Il n'y a qu'une seule façon d'éviter les critiques : ne rien faire, ne rien dire, et n'être rien.", "autor": "Aristote"},
    {"citation": "La vie est trop courte pour la passer à regretter tout ce qu’on n’a pas eu le courage de tenter.", "autor": "Marie-Claude Bibeau"},
    {"citation": "Le vrai bonheur coûte peu ; s'il est cher, il n'est pas d'une bonne espèce.", "autor": "Chateaubriand"},
    {"citation": "Ceux qui ne peuvent se souvenir du passé sont condamnés à le répéter.", "autor": "George Santayana"},
    {"citation": "L'amour ne voit pas avec les yeux mais avec l'âme.", "autor": "William Shakespeare"},
    {"citation": "On n'est jamais content là où l'on est.", "autor": "Molière"},
    {"citation": "Il vaut mieux être haï pour ce que l’on est, qu’être aimé pour ce que l’on n’est pas.", "autor": "André Gide"},
    {"citation": "Il y a toujours une part de folie dans l'amour. Mais il y a aussi toujours une part de raison dans la folie.", "autor": "Friedrich Nietzsche"},
    {"citation": "Les grandes choses ne sont pas accomplies par ceux qui cèdent aux tendances, aux fads et aux passions du moment.", "autor": "Jack Kerouac"},
    {"citation": "L'homme est né libre, et partout il est dans les fers.", "autor": "Jean-Jacques Rousseau"},
    {"citation": "Le cœur a ses raisons que la raison ne connaît point.", "autor": "Blaise Pascal"},
    {"citation": "Le plus grand malheur des hommes est qu'ils ne réfléchissent pas.", "autor": "Blaise Pascal"},
    {"citation": "La vraie générosité envers l'avenir consiste à tout donner au présent.", "autor": "Albert Camus"},
    {"citation": "Il n'y a qu'un seul bonheur dans la vie, c'est d'aimer et d'être aimé.", "autor": "George Sand"},
    {"citation": "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.", "autor": "Antoine de Saint-Exupéry"},
    {"citation": "Rien n'est plus dangereux qu'une idée, quand on n'a qu'une idée.", "autor": "Alain"},
    {"citation": "L'ignorance est la mère de tous les maux.", "autor": "François Rabelais"},
    {"citation": "Le meilleur moyen de réaliser l'impossible est de croire que c'est possible.", "autor": "Alice au Pays des Merveilles"},
    {"citation": "Je pense, donc je suis.", "autor": "René Descartes"},
    {"citation": "L'homme est un loup pour l'homme.", "autor": "Thomas Hobbes"},
    {"citation": "La liberté des uns s'arrête là où commence celle des autres.", "autor": "John Stuart Mill"},
    {"citation": "Un peu de science éloigne de Dieu, mais beaucoup y ramène.", "autor": "Louis Pasteur"},
    {"citation": "La connaissance s'acquiert par l'expérience, tout le reste n'est que de l'information.", "autor": "Albert Einstein"},
    {"citation": "La grandeur d'un métier est peut-être, avant tout, d'unir des hommes : il n'est qu'un luxe véritable et c'est celui des relations humaines.", "autor": "Antoine de Saint-Exupéry"},
    {"citation": "L'avenir n'est jamais que du présent à mettre en ordre. Tu n'as pas à le prévoir mais à le permettre.", "autor": "Antoine de Saint-Exupéry"},
    {"citation": "C'est le temps que tu as perdu pour ta rose qui fait ta rose si importante.", "autor": "Antoine de Saint-Exupéry"},
    {"citation": "Il faut toujours viser la lune, car même en cas d'échec, on atterrit dans les étoiles.", "autor": "Oscar Wilde"},
    {"citation": "La vie est un mystère qu'il faut vivre, et non un problème à résoudre.", "autor": "Gandhi"},
    {"citation": "Les seules limites à nos réalisations de demain sont nos doutes d'aujourd'hui.", "autor": "Franklin D. Roosevelt"},
    {"citation": "Le bonheur est parfois caché dans l'inconnu.", "autor": "Victor Hugo"},
    {"citation": "L'important, ce n'est pas de convaincre, mais de donner à réfléchir.", "autor": "Bernard Werber"},
    {"citation": "L'enfer, c'est les autres.", "autor": "Jean-Paul Sartre"},
    {"citation": "Vivre sans espoir, c'est cesser de vivre.", "autor": "Fiodor Dostoïevski"},
    {"citation": "On ne naît pas femme : on le devient.", "autor": "Simone de Beauvoir"},
    {"citation": "Il n’y a qu’une chose qui puisse rendre un rêve impossible, c’est la peur d’échouer.", "autor": "Paulo Coelho"},
    {"citation": "Les folies sont les seules choses qu'on ne regrette jamais.", "autor": "Oscar Wilde"},
    {"citation": "La vie, c’est comme une bicyclette, il faut avancer pour ne pas perdre l’équilibre.", "autor": "Albert Einstein"},
    {"citation": "Je ne cherche pas à connaître les réponses, je cherche à comprendre les questions.", "autor": "Confucius"},
    {"citation": "Les hommes construisent trop de murs et pas assez de ponts.", "autor": "Isaac Newton"},
    {"citation": "La seule chose que nous ayons à craindre est la crainte elle-même.", "autor": "Franklin D. Roosevelt"},
    {"citation": "Ce que l'on fait dans sa vie résonne dans l'éternité.", "autor": "Maximus Decimus"},
    {"citation": "On peut vaincre mille fois mille hommes dans une bataille, mais le plus grand des conquérants est celui qui se vainc lui-même.", "autor": "Bouddha"},
    {"citation": "Le secret du changement consiste à concentrer son énergie pour créer du nouveau, et non pour se battre contre l'ancien.", "autor": "Socrate"},
    {"citation": "L'intelligence, c'est la capacité de s'adapter au changement.", "autor": "Stephen Hawking"},
    {"citation": "La vie est une fleur. L'amour en est le miel.", "autor": "Victor Hugo"},
    {"citation": "Nous sommes ce que nous faisons de manière répétée. L'excellence n'est donc pas un acte, mais une habitude.", "autor": "Aristote"},
    {"citation": "Tout ce que l’esprit peut concevoir et croire, il peut l’accomplir.", "autor": "Napoleon Hill"},
    {"citation": "La vraie liberté consiste à pouvoir tout faire sans nuire à autrui.", "autor": "Charles de Montesquieu"},
    {"citation": "Le seul endroit où le succès précède le travail est dans le dictionnaire.", "autor": "Vidal Sassoon"},
    {"citation": "La vie est une suite de leçons qui doivent être vécues pour être comprises.", "autor": "Helen Keller"},
    {"citation": "Fais de ta vie un rêve, et d'un rêve, une réalité.", "autor": "Antoine de Saint-Exupéry"},
    {"citation": "Le bonheur n’est pas un but, c’est une façon de vivre.", "autor": "Margaret Lee Runbeck"},
    {"citation": "Seuls ceux qui se risquent à aller trop loin découvrent jusqu'où on peut aller.", "autor": "T. S. Eliot"},
    {"citation": "Ne jugez pas chaque jour à la récolte que vous faites, mais aux graines que vous semez.", "autor": "Robert Louis Stevenson"},
    {"citation": "Rien n'est permanent, sauf le changement.", "autor": "Héraclite"},
    {"citation": "La seule façon de faire du bon travail, c'est d'aimer ce que vous faites.", "autor": "Steve Jobs"},
    {"citation": "La meilleure façon de prédire l'avenir est de le créer.", "autor": "Peter Drucker"},
    {"citation": "La simplicité est la sophistication suprême.", "autor": "Léonard de Vinci"},
    {"citation": "Soyez le changement que vous voulez voir dans le monde.", "autor": "Mahatma Gandhi"},
    {"citation": "Les rêves ne deviennent pas réalité par magie ; il faut de la détermination et du travail.", "autor": "Colin Powell"},
    {"citation": "Un pessimiste voit la difficulté dans chaque opportunité, un optimiste voit l’opportunité dans chaque difficulté.", "autor": "Winston Churchill"},
    {"citation": "Ne pas planifier, c'est planifier l'échec.", "autor": "Benjamin Franklin"},
    {"citation": "Le succès, c'est tomber sept fois, se relever huit.", "autor": "Proverbe japonais"},
    {"citation": "Le plus grand obstacle à la réussite est la peur de l'échec.", "autor": "Sven Goran Eriksson"},
    {"citation": "Le bonheur n’est pas dans la possession de biens, mais dans la jouissance des choses.", "autor": "Jean-Jacques Rousseau"},
    {"citation": "L’action est la clé fondamentale de tout succès.", "autor": "Pablo Picasso"},
    {"citation": "Il est plus facile de se changer soi-même que de changer le monde.", "autor": "Gandhi"},
    {"citation": "La réussite appartient à tout le monde. C'est au travail d'équipe qu'en revient le mérite.", "autor": "François Mitterrand"},
    {"citation": "Le plus grand échec est de ne pas avoir le courage d'oser.", "autor": "André Gide"},
    {"citation": "Il n’y a pas de substitut à l’honnêteté.", "autor": "Warren Buffett"},
    {"citation": "La sagesse commence dans l’émerveillement.", "autor": "Socrate"},
    {"citation": "Les mots sont des fenêtres (ou bien ce sont des murs).", "autor": "Marshall Rosenberg"},
    {"citation": "Le plus grand ennemi du succès est la peur de l’échec.", "autor": "Charles F. Kettering"},
    {"citation": "Les seules choses qui ont de la valeur sont celles qu'on partage.", "autor": "Jean-Paul Sartre"},
    {"citation": "Les rêves ont besoin de travail pour se réaliser.", "autor": "Pablo Neruda"},
    {"citation": "Ce n’est pas la montagne que nous conquérons, mais nous-mêmes.", "autor": "Sir Edmund Hillary"},
    {"citation": "La vie est ce que nous en faisons. Toujours a été, toujours le sera.", "autor": "Eleanor Roosevelt"},
    {"citation": "Il n'y a pas de chemin vers le bonheur. Le bonheur est le chemin.", "autor": "Bouddha"},
    {"citation": "Le bonheur est fait de petites choses ; un sourire, une rencontre, un bon repas.", "autor": "Jean de La Fontaine"},
    {"citation": "Le seul vrai voyage consiste à découvrir les paysages inconnus que nous avons en nous.", "autor": "Marcel Proust"},
    {"citation": "Il n'est jamais trop tard pour être ce que vous auriez pu être.", "autor": "George Eliot"},
    {"citation": "L'important n'est pas d'avoir une vie longue, mais une vie remplie de sens.", "autor": "Sénèque"},
    {"citation": "La plus grande erreur que vous puissiez faire dans la vie est d’avoir toujours peur de faire une erreur.", "autor": "Elbert Hubbard"},
    {"citation": "Le plus grand obstacle au progrès est la peur du changement.", "autor": "John F. Kennedy"},
    {"citation": "La vie est faite de choix. Nos choix font notre vie.", "autor": "Jean-Paul Sartre"},
    {"citation": "L'avenir appartient à ceux qui croient à la beauté de leurs rêves.", "autor": "Eleanor Roosevelt"},
    {"citation": "Le bonheur est un choix, pas une conséquence.", "autor": "Ralph Marston"},
    {"citation": "Tout ce qui ne nous tue pas nous rend plus fort.", "autor": "Friedrich Nietzsche"},
    {"citation": "Les grandes choses ne se font pas par impulsion, mais par une série de petites choses réunies.", "autor": "Vincent Van Gogh"},
    {"citation": "La vie est une aventure audacieuse ou elle n'est rien.", "autor": "Helen Keller"},
    {"citation": "Tout ce que nous sommes est le résultat de ce que nous avons pensé.", "autor": "Bouddha"},
    {"citation": "La vie est courte, mais elle est assez longue pour bien faire.", "autor": "Épictète"},
    {"citation": "Le meilleur moyen de prédire l'avenir est de l'inventer.", "autor": "Alan Kay"},
    {"citation": "La vie n’est pas d’attendre que l’orage passe, mais d’apprendre à danser sous la pluie.", "autor": "Vivian Greene"},
    {"citation": "La vraie grandeur consiste à être supérieur à celui que nous étions hier.", "autor": "Ernest Hemingway"},
    {"citation": "La vie est trop courte pour la passer à regretter.", "autor": "Proverbe chinois"},
    {"citation": "Les seuls vrais échecs sont ceux que l'on n'essaie pas de surmonter.", "autor": "John C. Maxwell"},
    {"citation": "La meilleure façon de se faire des amis est d’en être un.", "autor": "Ralph Waldo Emerson"},
    {"citation": "Il n'y a pas de réussite sans échec.", "autor": "Louis Pasteur"},
    {"citation": "Chaque jour est une nouvelle chance de changer ta vie.", "autor": "Inconnu"},
    {"citation": "On ne peut pas traverser la mer simplement en regardant l’eau.", "autor": "Rabindranath Tagore"},
    {"citation": "La seule façon de faire un excellent travail est d’aimer ce que vous faites.", "autor": "Steve Jobs"},
    {"citation": "Si vous voulez vivre une vie heureuse, attachez-la à un but, pas à des personnes ou des choses.", "autor": "Albert Einstein"},
    {"citation": "Les grandes pensées viennent du cœur.", "autor": "Luc de Clapiers"},
    {"citation": "Ce n’est pas la longueur de la vie, mais la profondeur de la vie.", "autor": "Ralph Waldo Emerson"},
    {"citation": "La seule chose que vous pouvez réellement contrôler est votre attitude.", "autor": "Inconnu"},
    {"citation": "Le plus grand voyage est celui qui mène à la découverte de soi.", "autor": "Proverbe chinois"},
    {"citation": "Le bonheur est souvent le résultat d’une attitude positive.", "autor": "Inconnu"},
    {"citation": "Le vrai courage, c'est de regarder la réalité en face.", "autor": "Alain"},
    {"citation": "La vie n'est pas d'attendre que les orages passent, c'est d'apprendre à danser sous la pluie.", "autor": "Vivian Greene"},
    {"citation": "Le bonheur est une direction, pas une destination.", "autor": "Sydney J. Harris"},
    {"citation": "La réussite appartient à ceux qui croient en la beauté de leurs rêves.", "autor": "Eleanor Roosevelt"},
    {"citation": "Tout ce que vous pouvez faire ou rêver de faire, commencez-le. L'audace a du génie, de la puissance et de la magie.", "autor": "Johann Wolfgang von Goethe"},
    {"citation": "Le véritable voyage de découverte ne consiste pas à chercher de nouveaux paysages, mais à avoir de nouveaux yeux.", "autor": "Marcel Proust"},
    {"citation": "Ce qui ne nous tue pas nous rend plus fort.", "autor": "Friedrich Nietzsche"},
    {"citation": "Chaque difficulté rencontrée doit être l'occasion d'un nouveau progrès.", "autor": "Pierre de Coubertin"},
    {"citation": "La vie est trop courte pour passer du temps avec des gens qui ne sont pas bienveillants.", "autor": "Inconnu"},
    {"citation": "Le bonheur est une manière de voyager, non une destination.", "autor": "Roy Goodman"},
    {"citation": "Il est plus facile de demander pardon que de demander la permission.", "autor": "Grace Hopper"},
    {"citation": "La meilleure façon de se réaliser est d'aider les autres à réaliser leurs rêves.", "autor": "Inconnu"},
    {"citation": "Les seules limites qui existent sont celles que vous vous imposez.", "autor": "Inconnu"},
    {"citation": "Les gens ne sont pas contre vous ; ils sont pour eux-mêmes.", "autor": "Inconnu"},
    {"citation": "Ce qui importe, ce n'est pas ce que l'on a, mais ce que l'on fait avec ce que l'on a.", "autor": "Inconnu"},
    {"citation": "Il n’y a pas de meilleur moment pour commencer que maintenant.", "autor": "Inconnu"},
    {"citation": "La passion est la clé du succès.", "autor": "Inconnu"},
    {"citation": "Le plus grand des voyages commence par un premier pas.", "autor": "Lao Tseu"},
    {"citation": "Les rêves sont les réponses d'aujourd'hui aux questions de demain.", "autor": "Inconnu"},
    {"citation": "La vie est ce que vous en faites.", "autor": "Eleanor Roosevelt"}
]